services:
  product_database:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: localadmin
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpass
      MYSQL_DATABASE: product
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: