name: build product service
on:
  workflow_dispatch:
  push:
    paths:
      - 'product/**'
      - 'commons/**'
    branches:
      - cicd
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup docker build
        uses: docker/setup-buildx-action@v2
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./product/Dockerfile
          push: 'true'
          tags: lamph11/product-service:latest
