name: build webconfig service
on:
  workflow_dispatch:
  push:
    paths:
      - 'webconfig/**'
      - 'commons/**'
    branches:
      - cicd
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup docker build
        uses: docker/setup-buildx-action@v2
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Generate image tag
        id: vars
        run: |
          TAG=$(date +'%Y%m%d-%H%M%S')
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./auth/Dockerfile
          push: 'true'
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/webconfig-service:latest
            ${{ secrets.DOCKER_USERNAME }}/webconfig-service:${{ steps.vars.outputs.TAG }}
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/webconfig-service:latest
            cd /root/backend/micro-ecom
            docker-compose up -d --force-recreate webconfig-service